### ISSUE TITLE
fish (shell) support?

### ISSUE THREAD

**Issue by kimusan** [BartSte/fzf-help#10]
Any chance this could be supported on fish shell as well? I am pretty sure the changes are minimal and mostly around the install script.

**Comment by BartSte** [comment]
I've never used fish but I can look into it.

**Comment by kimusan** [comment]
I'll see if I can make a script for it.  PR coming up

**Comment by BartSte** [comment]
Nice!

**Comment by BartSte** [comment]
Resolved by version: [2.0.0](https://github.com/BartSte/fzf-help/tree/2.0.0)
