### ISSUE TITLE
Install on linux without admin rights

### ISSUE THREAD

**Issue by elkarouh** [BartSte/fzf-help#11]
I want to install this on my work computer.
Is there a way to install the zsh plugin in another directory?

**Comment by BartSte** [comment]
Yeah, maybee it would be better to install it in another directory than /usr/share/. Maybee I'll change that. For the meantime, you can just clone this repo anywhere you want, source the `fzf-help.zsh` file, and set the binding:
```
source /some-directory/fzf-help/src/fzf-help.zsh
zle -N fzf-help-widget
bindkey "^A" fzf-help-widget
```

**Comment by BartSte** [comment]
I added a user installation to the main branch! Commit: bc8382e8c844d20ce45750c40cb0aebb7c78cd65
