### ISSUE TITLE
bat-cli-options missing

### ISSUE THREAD

**Issue by kimusan** [BartSte/fzf-help#12]
The changelog mentions bat-cli-.options but that does not exist. bat complains that syntax=help does not exist

**Comment by BartSte** [comment]
bat-cli-options was renamed to `fzf-select-option-preview`. On the last line of this file the help highlighting is set:
```
bat -f -pp -H $line_number -r $scroll: --language=help
```

**Comment by BartSte** [comment]
What version of bat do you use? Maybee older versions do not support `--language=help` yet? I use:
```
❯ bat --version
bat 0.23.0 (871abd27)
```

**Comment by kimusan** [comment]
bat --version                                                                                                                                                                                                          bat 0.19.0

**Comment by kimusan** [comment]
I upgraded to 0.23 and it seems to fix the problem. Maybe add the dependency on version to the README
