### ISSUE TITLE
Sorted + unique set of options

### ISSUE THREAD

**Issue by kimusan** [BartSte/fzf-help#14]
it seems like the script finds all mentions of an option so if the help has a comment like "see also -f for more info" then it will show -f twice in the list.  The options for ls command is a good example of this.
Maybe run the options list through uniq and maybe even sort it to get a more fitting list.

**Comment by BartSte** [comment]
I like this behaviour as I allows me to scroll through all mentions of the options in the help docs. You can set your custom regex if you want as is described in the readme.

**Comment by BartSte** [comment]
Or we could add an optional "unique filter" after the `ag` command in the cli-options script.

**Comment by kimusan** [comment]
that could be a good solution

**Comment by BartSte** [comment]
Checkout the develop branch. I added a way to customize the command that is used by the  `cli-options` command by setting the `CLI_OPTIONS_CMD` variable. This way you can apply that extra (unique) filter you mentioned.

**Comment by BartSte** [comment]
Resolved by: f94c31c
