### ISSUE TITLE
batcat 0.19 not working

### ISSUE THREAD

**Issue by BartSte** [BartSte/fzf-help#16]
batcat 0.19 is the version that is currently used by ubuntu. This version does not support `--language=help`. We need a workaround for this.

**Comment by ronisaacson** [comment]
One (ugly) workaround is to remove the ubuntu package and manually install a newer version, e.g. from https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-musl_0.23.0_amd64.deb.

**Comment by BartSte** [comment]
I though about setting the default syntax to 'txt'. If you have a newer version of bat you can use the env variable to set it to 'help'

**Comment by BartSte** [comment]
Resolved by: 816983ba528d8cf4a1e35d4a4e4637b9061de3de
