### ISSUE TITLE
The option list and preview window scroll in the opposite order

### ISSUE THREAD

**Issue by ronisaacson** [BartSte/fzf-help#17]
fzf-help uses the default fzf ordering which puts the option list in reverse order. This means that you need to scroll up to move through the options, and the preview window scrolls down as you do. It's confusing to have the list and the preview moving in opposite directions. Maybe consider adding `--reverse` to the default `FZF_HELP_OPTS` in fzf-select-option. This makes it behave the same as fzf-file-widget where you start at the top and scroll down.

**Comment by BartSte** [comment]
Already fixed by: https://github.com/BartSte/fzf-help/pull/15
