### ISSUE TITLE
modify default keybinding

### ISSUE THREAD

**Issue by diskmanti** [BartSte/fzf-help#18]
Hello,

I am trying to bind fzf-help to another keybind, for example C-q, but it seems I am unable to.
I have added the following exports in my shell but nothing happens when i prewss C-q:
```bash
FZF_HELP_OPTS+="--bind ctrl-q:change-preview-window(down,75%,nowrap|right,75%,nowrap)"
 bind -x '"\C-q": fzf-help-widget'
```

Can you please suggest if I am doing smth wrong.

Thank you
PS: This is a great utility 😄

**Comment by BartSte** [comment]
Thanks!

What shell do you use? From your bind command I guess `bash`? 

Before you can bind to `fzf-help-widget` you need to `source /usr/share/fzf-help/fzf-help.bash`. So I would suggest you first try if the following work for you:

```bash
source /usr/share/fzf-help/fzf-help.bash
bind -x '"\C-q": fzf-help-widget'
```

If this works, you can try to alter the `FZF_HELP_OPTS`.

**Comment by diskmanti** [comment]
thank you for the fast resposne. I added the lines as you suggested but pressin C-q still doesn't work

**Comment by BartSte** [comment]
I see now you cannot bind to ctrl+q using bash. You need to choose another bind.

https://unix.stackexchange.com/questions/213848/why-arent-ctrlm-and-ctrlq-used-in-bash-shortcuts
