### ISSUE TITLE
Does not work on MacOS

### ISSUE THREAD

**Issue by edosrecki** [BartSte/fzf-help#24]
### Versions
**fzf-help**: 2.1.0
**MacOS**: 14.2.1

### Errors
```sh
grep: invalid option -- P

usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
```

```sh
mktemp: option requires an argument -- t

usage: mktemp [-d] [-p tmpdir] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-p tmpdir] [-q] [-u] -t prefix

**Comment by BartSte** [comment]
Thanks. Only tested in on Linux. Maybe I'll test on MacOs in the future as wel.

**Comment by edosrecki** [comment]
If I find time I will try to convert it to make it use features that are compatible with both Linux and MacOS. For now I just opened the ticket to have it tracked.

**Comment by edosrecki** [comment]
@BartSte 

For now I locally fixed it for myself by doing the following:

1. Install GNU versions of `mktemp` and `grep`. These get installed prefixed with letter `g`: `gmktemp` and `ggrep`:
```sh
brew install coreutils
brew install grep
```

2. Replace `grep` with `ggrep`, and `mktemp` with `gmktemp` in local installation of `fzf-help`.

**Comment by edosrecki** [comment]
@BartSte I created a PR: https://github.com/BartSte/fzf-help/pull/25
