### ISSUE TITLE
Can this work with aliases?

### ISSUE THREAD

**Issue by phlawlessDevelopment** [BartSte/fzf-help#26]
I have "php artisan" aliased to "art", this fails to recognise "art" as a command.

My aliases are defined in .zshrc, in case that's relevant.

**Comment by BartSte** [comment]
Hey, 

No it does not work with aliases, but this could be a good feature though.

As a workaround, you could add the following script (and call it `art`) to your PATH and make it executable:

```bash
#!usr/bin/env bash
php artisan $@
```

**Comment by phlawlessDevelopment** [comment]
Unfortunately i don't understand bash enough to help, i tried a few things with the "command" built in but no luck.

That's a decent workaround, which will do just fine for me. So thank you.

**Comment by BartSte** [comment]
Reopening this as I run into this issue often. I think this feature should be possible by setting the help command correctly. I'll look into it.

**Comment by BartSte** [comment]
See 8c530d5
