### ISSUE TITLE
shebang does not work on more recent macs

### ISSUE THREAD

**Issue by chrisgrieser** [BartSte/fzf-help#3]
When trying to run the installer and/or the cli, I got an error that `bash` was not found. I looked into it, and it seems the shebang is the cause of that issue.

Not sure which macOS versions this concerns, but on my macOS version, `which bash` results in `/bin/bash`, not `usr/bin/bash`.

Consequently, replacing all shebangs with `#!/usr/bin/env bash` did fix the issue for me.

**Comment by BartSte** [comment]
Ah thanks for this! I did not test it on mac as I use Linux. I'll look into it.
