### ISSUE TITLE
empty search list

### ISSUE THREAD

**Issue by tariks** [BartSte/fzf-help#7]
<img width="1069" alt="Screenshot" src="https://github.com/BartSte/fzf-help/assets/3433086/4bf63c47-4286-4e89-a871-cbae1def88fb">

The search list does not populate when I trigger fzf-help, though the preview panel shows as expected.

Environment: macbook with zsh shell from homebrew. kitty terminal.

Notes: I installed things slightly differently than in the readme. I cloned the repo locally then appended to my zshrc:

```
FZF_HELP_OPTS="--preview-window=right,68%,nowrap --height 80% "
FZF_HELP_OPTS+="--bind ctrl-h:change-preview-window(down,75%,nowrap|right,75%,nowrap)"
source <path-to-cloned-repo/src>fzf-help.zsh
zle -N fzf-help-widget
bindkey "^H" fzf-help-widget
```

my config includes fzf-tab, fzf-tab-source, and jeffreytse/zsh-vi-mode. I use the ^H binding to avoid a conflict with ^A

**Comment by BartSte** [comment]
I'll try to reproduce it. I did not test fzf-help on mac as I use Linux. Though, it should work on mac. 

Did you install ag? Did you get any error messages? Does it happen with all command? Or only exa?

**Comment by tariks** [comment]
Thanks for your time.

It is every command, and I use ag from homebrew.

I think the cause is more likely something in my config; I don't see any mac-unfriendly code in the src/ scripts. It's such an odd result. One thought I had is macos's sed vs GNU sed.

**Comment by BartSte** [comment]
Most likely it is an issue with the `cli-options` executable. The following should happen:
![image](https://github.com/BartSte/fzf-help/assets/62509788/7b0ef465-8762-496e-aa76-40da71e57dd0)

When I have time, I'll spin up a VM with MacOS to find out what's going on.

**Comment by BartSte** [comment]
It's suprisingly difficult to setup a VM with macOS on Linux. I tried projects like [macos-virtualbox](https://github.com/myspaghetti/macos-virtualbox) with no succes. I'll have a go at it some other time on my Windows device and [this tutorial](https://www.makeuseof.com/tag/macos-windows-10-virtual-machine).

**Comment by BartSte** [comment]
No success on my windows machine, unfortunately. Debugging this issue will have to wait 🙁

**Comment by BartSte** [comment]
your issue might be fixed by all the fixes I applied last period.
