### ISSUE TITLE
Windows terminal + OMZ

### ISSUE THREAD

**Issue by RuiApostolo** [BartSte/fzf-help#8]
More of a question than an issue per se, but would this work on Windows Terminal running Ubuntu 22.04 and Oh-my-zsh?

**Comment by BartSte** [comment]
Yes it will work on Windows Terminal + Ubuntu 22.04 as long as you follow the configuration as is described in the readme. This way, it will not be a part of oh-my-zsh, but it will still work. I did not configure `fzf-help` as a oh-my-zsh plugin because I do no use oh-my-zsh.
